
#spring整合mybatis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: userserver #user 服务的服务名称
#  cloud:
#    nacos:
#      server-addr: http://localhost:8848 #nacos服务地址
#      discovery:
#        cluster-name: SH #集群名称          热部署文件中
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#设置映射资源文件
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xyu.user.domain


#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka