server:
  port: 8081
#spring整合mybatis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderserver #端口代号
  cloud:
    nacos:
      server-addr: http://localhost:8848 #nacos服务地址
      discovery:
        # cluster-name: HZ #集群名称
        # namespace:  环境隔离 填写的是命名空间的id
        # ephemeral: false  设置是否是临时实例 区别 注册中心主动询问和心跳检测
#设置映射资源文件
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xyu.order.domain

#eureka: #eureka客户端设置
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka #eureka服务地址

userserver:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userserver
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数